trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    cd /home/Thushar/DevOps/MyMavenApp
    mvn clean install
  displayName: 'Build with Maven'

- script: |
    cd /home/Thushar/DevOps/MyMavenApp
    java -jar target/MyMavenApp-3.0-SNAPSHOT.jar
  displayName: 'Run jar file'
